### ISSUE TITLE
Errors on upgrade

### ISSUE THREAD

**Issue by coladarci** [kipcole9/money_sql#33]
Heyya - 

When running the following update:
```
  ex_money 5.12.3 => 5.13.0
  ex_money_sql 1.8.0 => 1.9.2
```
I suddenly get the following:
```
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for {"USD", Decimal.new("50.00")} of type Tuple
```

There isn't a good stack trace to point to anything specific, but I'm hoping you have some ideas? 

Appreciate any ideas!

**Comment by kipcole9** [comment]
I've [updated the readme](https://hexdocs.pm/ex_money_sql/readme.html) to be as super clear and obvious as possible. And I've updated the [changelog](https://github.com/kipcole9/money_sql/blob/v1.9.2/CHANGELOG.md) too. 

Hopefully that means other people won't have the same issue I put you through.
