### ISSUE TITLE
Ecto types return malformed error when casting invalid currency

### ISSUE THREAD

**Issue by bgracie** [kipcole9/money_sql#4]
When casting an invalid currency, the both ecto types return an error tuple with another tuple as the second element.

https://github.com/kipcole9/money_sql/blob/bbc4f69b0152cb052c945fa17c51417103dc0b4b/test/money_ecto_test.exs#L72

This violates the [typespec](https://hexdocs.pm/ecto/Ecto.Type.html#c:cast/1) for `Ecto.Type.cast`: `cast(term()) :: {:ok, term()} | {:error, keyword()} | :error`, and causes an exception when used in `Ecto.Changeset.cast`

Please see [this demo repo](https://github.com/civilcode/money_cast_error) for a demonstration of the issue.

Incidentally, it appears that the `load` functions also violate the error typespec from Ecto.Type.

**Comment by kipcole9** [comment]
@bgracie I apologise, I only just noticed this (I need to check notifications on this repo). I’ll fix this right away.

**Comment by bgracie** [comment]
@kipcole9 Thanks!
